# Generated by Django 5.2.17 on 2026-09-29 13:55

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(editable=False, verbose_name="number"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("evolution", "Change request"),
                            ("bug", "Bug / anomaly"),
                            ("question", "Question"),
                            ("support", "Support request"),
                            ("feature", "New feature"),
                            ("task", "Internal task"),
                        ],
                        default="evolution",
                        max_length=12,
                        verbose_name="type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("to_analyse", "To analyse"),
                            ("todo", "To do"),
                            ("in_progress", "In progress"),
                            ("waiting_client", "Waiting for client"),
                            ("in_test", "In test"),
                            ("done", "Done"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("digitalia", "Digitalia"),
                            ("system", "System"),
                        ],
                        editable=False,
                        max_length=10,
                        verbose_name="origin",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("client", "Visible to client"),
                            ("internal", "Internal Digitalia"),
                        ],
                        default="client",
                        max_length=10,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="target date"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="closed at"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to=models.Q(
                            ("role", "staff"), ("is_superuser", True), _connector="OR"
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assignee",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "author_company",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.company",
                        verbose_name="author company",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="core.milestone",
                        verbose_name="roadmap step",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tickets.ticket",
                        verbose_name="parent ticket",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="core.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket",
                "verbose_name_plural": "tickets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="comment")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Internal notes are never shown to the client.",
                        verbose_name="internal note",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tickets.ticket",
                        verbose_name="ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=tickets.models.attachment_path, verbose_name="file"
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(default=False, verbose_name="internal"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.comment",
                        verbose_name="comment",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticket",
                        verbose_name="ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "attachment",
                "verbose_name_plural": "attachments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("changed", "Changed"),
                            ("commented", "Commented"),
                            ("attached", "File added"),
                        ],
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "field",
                    models.CharField(blank=True, max_length=50, verbose_name="field"),
                ),
                ("old_value", models.TextField(blank=True, verbose_name="old value")),
                ("new_value", models.TextField(blank=True, verbose_name="new value")),
                (
                    "is_internal",
                    models.BooleanField(default=False, verbose_name="internal"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="date"),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tickets.ticket",
                        verbose_name="ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "history entry",
                "verbose_name_plural": "history",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("project", "number"), name="unique_ticket_number"
            ),
        ),
    ]
