# Generated by Django 5.2.17 on 2026-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="file name"
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="size",
            field=models.PositiveBigIntegerField(default=0, verbose_name="size"),
        ),
    ]
